### PR TITLE
Update dependency_graph

### PR DESCRIPTION
**Pull request by prasys**
Problem Statement: The dependency graph.py to generate .graph that is used for ASGCN is currently hardcoded. This prohibits new data set from being used. To make it more dynamic, I have made dependency-graph to specify the location of the dataset that requires processing 

I've tested this on custom data sets and it makes it easier to do the processing.

Moving forward, I'll also include different spacy NLP model and also make it dynamic

### CODE REVIEW

**Comment by yangheng95** [comment]
Nice job! But have you tried to embed this script as an interface? e.g., Call the process function in the datautils.py to generate the graph file if the ASGCN is specified?

**Review by GeneZC — COMMENTED** [review]
The change to the code seems quite incremental.

**Comment by prasys** [comment]
Thanks @GeneZC  for reviewing, I just plan to keep it in smaller changes. However if needed to be, I can merge it together with the other changes (i.e datautils.py) to be updated 

@yangheng95 - I am working on that bit. Let me test it out if it's okay  - I'll just submit another PR Request

**Comment by yangheng95** [comment]
Good! In case of any help, you can refer to [here](https://github.com/yangheng95/PyABSA/blob/41a067aec58b067058c1998eba33b2d9908f4989/pyabsa/tasks/apc/__glove__/dataset_utils/data_utils_for_training.py#L174)

**Comment by songyouwei** [comment]
@all-contributors please add @prasys for code

**Pull request merged**
